kind: pipeline
name: example-pipeline2
type: docker
steps:
- name: build
  image: node:latest
  privileged: true
  commands:
  - npm install
  - npm run test
  when:
    branch:
    - master
    event:
    - push
    - pull-request
