kind: pipeline
name: default
type: docker
steps:
- name: build
  image: worker-game-replication
  privileged: true
  commands:
    - pip3 install -r requirements.txt
    - python3 ./main/main.py
  when:
    branch:
      - master
    event:
      - push
      - pull-request
