amqp:
  url: 'amqp://meete:p4ssw0rd@localhost:5672/meete'
  connect_max_retries: 0

log:
  level: 'INFO'

datasource:
  master:
    url: 'postgresql://meete:p4ssw0rd@localhost:5432/partner_voucher'

mongo:
  host: 'localhost'
  port: 27017
  max-pool-size: 100
  db: 'meeteG'
  collection: 'wheelBooking'
  authmechanism: 'SCRAM-SHA-256'
  user: 'huy'
  password: '123'
